<?php

/**
 * BaseDiagnosis
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $patient_id
 * @property string $tooth
 * @property string $diagnosis
 * @property string $treatment
 * @property string $active
 * @property Patient $Patient
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method integer   getPatientId()  Returns the current record's "patient_id" value
 * @method string    getTooth()      Returns the current record's "tooth" value
 * @method string    getDiagnosis()  Returns the current record's "diagnosis" value
 * @method string    getTreatment()  Returns the current record's "treatment" value
 * @method string    getActive()     Returns the current record's "active" value
 * @method Patient   getPatient()    Returns the current record's "Patient" value
 * @method Diagnosis setId()         Sets the current record's "id" value
 * @method Diagnosis setPatientId()  Sets the current record's "patient_id" value
 * @method Diagnosis setTooth()      Sets the current record's "tooth" value
 * @method Diagnosis setDiagnosis()  Sets the current record's "diagnosis" value
 * @method Diagnosis setTreatment()  Sets the current record's "treatment" value
 * @method Diagnosis setActive()     Sets the current record's "active" value
 * @method Diagnosis setPatient()    Sets the current record's "Patient" value
 * 
 * @package    romident
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDiagnosis extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_diagnosis');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('patient_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'notnull' => false,
             ));
        $this->hasColumn('tooth', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             'notnull' => false,
             ));
        $this->hasColumn('diagnosis', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             'notnull' => false,
             ));
        $this->hasColumn('treatment', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             'notnull' => false,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 1,
             ));


        $this->index('i_active', array(
             'fields' => 
             array(
              0 => 'active',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Patient', array(
             'local' => 'patient_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'id',
              1 => 'tooth',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
    }
}