<?php

/**
 * BaseAppointment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $patient_id
 * @property timestamp $date_of_quote
 * @property string $title
 * @property string $descriptions
 * @property string $active
 * @property Patient $Patient
 * 
 * @method integer     getId()            Returns the current record's "id" value
 * @method integer     getPatientId()     Returns the current record's "patient_id" value
 * @method timestamp   getDateOfQuote()   Returns the current record's "date_of_quote" value
 * @method string      getTitle()         Returns the current record's "title" value
 * @method string      getDescriptions()  Returns the current record's "descriptions" value
 * @method string      getActive()        Returns the current record's "active" value
 * @method Patient     getPatient()       Returns the current record's "Patient" value
 * @method Appointment setId()            Sets the current record's "id" value
 * @method Appointment setPatientId()     Sets the current record's "patient_id" value
 * @method Appointment setDateOfQuote()   Sets the current record's "date_of_quote" value
 * @method Appointment setTitle()         Sets the current record's "title" value
 * @method Appointment setDescriptions()  Sets the current record's "descriptions" value
 * @method Appointment setActive()        Sets the current record's "active" value
 * @method Appointment setPatient()       Sets the current record's "Patient" value
 * 
 * @package    romident
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAppointment extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_appointment');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('patient_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'notnull' => false,
             ));
        $this->hasColumn('date_of_quote', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             'notnull' => false,
             ));
        $this->hasColumn('descriptions', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             'notnull' => false,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 1,
             ));


        $this->index('i_active', array(
             'fields' => 
             array(
              0 => 'active',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Patient', array(
             'local' => 'patient_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
    }
}