# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Romident
    description:  Romident
    keywords:     Romident
    language:     es
    robots:       index, follow

  stylesheets:
    - general/main.css:                 { position: first }
    - backend/general.css:              { position: first }
    - backend/button.css:               { position: first }
    - backend/menu.css:                 { position: first }
    - general/jquery-ui-1.8.custom.css: { position: first }
    - backend/fullcalendar.print.css:    { media: print }
    
  javascripts:
    - jquery/jquery-1.4.2.min.js
    - jquery/jquery-ui-1.8.min.js
    - general/general.js
    - jquery/i18n/jquery-ui-i18n.js

  has_layout:     true
  layout:         layout