<?php

/**
 * AppointmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AppointmentTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AppointmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Appointment');
    }
 const
    STATUS_ACTIVE       = 1,
    STATUS_INACTIVE     = 0;
    
  protected static
    $status                = array
                             (
                               self::STATUS_ACTIVE     => 'Pendiente',
                               self::STATUS_INACTIVE   => 'Terminado',
                             );
                             
  public function getStatuss()
  {
    return self::$status;
  }	    
}