<?php

/**
 * Appointment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    romident
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Appointment extends BaseAppointment
{
  public function getFormattedDatetime($format = 'D')
  {
    return $this->getTable()->getDateTimeFormatter()->format($this->getCreatedAt(), $format);
  }

  public function getFormattedDateOfQuote($format = 'D')
  {
    return $this->getTable()->getDateTimeFormatter()->format($this->getDateOfQuote(), $format);
  }  
  public function getStatusStr()
  {  	
  	$actives = $this->getTable()->getStatuss();
  	return $actives[$this->getActive()];
  }  
}