<?php

/**
 * DentalHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DentalHistoryTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DentalHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DentalHistory');
    }
}