<?php

/**
 * DentistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DentistTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DentistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Dentist');
    }
  const
    STATUS_ACTIVE       = 1,
    STATUS_INACTIVE     = 0;
    
  protected static
    $status                = array
                             (
                               self::STATUS_ACTIVE     => 'Si'  ,
                               self::STATUS_INACTIVE   => 'No',
                             );
                             
  public function getStatuss()
  {
    return self::$status;
  }	
  
  const
    GENDER_MALE       = 1,
    GENDER_FAME     = 0;
    
  protected static
    $gender                = array
                             (
                               self::GENDER_MALE   => 'Masculino',
                               self::GENDER_FAME   => 'Femenino' ,
                             );
                             
  public function getGenders()
  {
    return self::$gender;
  }

  public function findByNameLike($name, $limit = 20)
  {
    $q = $this->createAliasQuery('d')

         ->where('LOWER(d.firstname) LIKE ?', '%'.Stringkit::strtolower($name).'%')
          ->orwhere('LOWER(d.lastname) LIKE ?', '%'.Stringkit::strtolower($name).'%')
         ->limit($limit);
    
    return $q->execute();
  }  

  
    
}