<?php

/**
 * Holder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    romident
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Holder extends BaseHolder
{
  public function getActiveStr()
  {  	
  	$actives = $this->getTable()->getStatuss();
  	return $actives[$this->getActive()];
  }
  
  public function getFullName()
  {
      return $this->getFirstname().' '.$this->getLastname();
  }
  
  public function getGenderStr()
  {  	
  	$actives = $this->getTable()->getGenders();
  	return $actives[$this->getGender()];
  }
}