<?php

/**
 * MedicalHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedicalHistoryTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedicalHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedicalHistory');
    }
}