<?php

/**
 * PatientMedicalHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PatientMedicalHistoryTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PatientMedicalHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PatientMedicalHistory');
    }
}