<?php

/**
 * PatientDentalHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PatientDentalHistoryTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PatientDentalHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PatientDentalHistory');
    }
}