<?php

/**
 * Patient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    romident
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Patient extends BasePatient
{

  public function getFormattedDateOfBirth($format = 'D')
  {
    return $this->getTable()->getDateTimeFormatter()->format($this->getDateOfBirth(), $format);
  }
  
  public function getMedicalHistoryName()
  {
  	$medical_histories = '<ul style="padding-left:8px;">';
  	foreach($this->getMedicalHistories() as $history)
  	{
  	  $medical_histories .= '<li>'.$history->getName().'</li>';
  	}
  	
  	return $medical_histories.'</ul>';
  }
  
  public function getDentalHistoryName()
  {
  	$medical_histories = '<ul style="padding-left:8px;">';
  	foreach($this->getDentalHistories() as $history)
  	{
  	  $medical_histories .= '<li>'.$history->getName().'</li>';
  	}
  	
  	return $medical_histories.'</ul>';
  }

  public function getFullName()
  {
      return $this->getFirstname().' '.$this->getLastname();
  }

  public function getGenderStr()
  {  	
  	$actives = $this->getTable()->getGenders();
  	return $actives[$this->getGender()];
  }
  
  public function getTypeStr()
  {  	
  	$actives = $this->getTable()->getTypes();
  	return $actives[$this->getType()];
  }
  
  public function getIdMedicalHistory($value = 'Medical')
  {

  	$my_history = ($value == 'Medical')?$this->getMedicalHistories():$this->getDentalHistories();
  	$ids = array();
  	foreach($my_history as $key => $record)
  	{
  		$ids[$key] = $record->getId();
  	}
  	return $ids;
  }
  
  public function getReporteDiagnostio()
  {
  	$diagnosticos = $this->getDiagnosis();
  	$data = null;
  	
  	foreach($diagnosticos as $key => $diagnostico)
  	{
      $data[$key] = array($diagnostico->getFormattedDatetime('dd-MM-yyyy'), $diagnostico->getTooth(), $diagnostico->getDiagnosis(), $diagnostico->getTreatment(),'');
  	}
  	
  	return $data;
  }

  
  public function getReportMedicalHistory($value = 'Medical')
  {
  	if($value == 'Medical')
  	{
  	  $medical_history = Doctrine::getTable('MedicalHistory')->findAll();
  	  $my_history = $this->getIdMedicalHistory();  		
  	}
  	else
  	{
  	  $medical_history = Doctrine::getTable('DentalHistory')->findAll();
  	  $my_history = $this->getIdMedicalHistory('Dental');  		
  	}

  	$data = null;
  	
  	foreach($medical_history as $key => $record)
  	{
  		if(in_array($record->getId(), $my_history))
  		{
  			$si = 'X';
  			$no = '';
  		}
  		else
  		{
  			$si = '';
  			$no = 'X';  			
  		}
  	  $data[$key] = array($record->getName(), $si, $no);
  	}
  	return $data;
  }
}