Diagnosis:
  tableName:                           t_diagnosis
  actAs:
    SluggableExt:                      { fields: [ id, tooth] }
    Timestampable:
  columns:
    id:                                { type: integer  , length: 20 , primary: true    , autoincrement: true                                                  }
    patient_id:                        { type: integer  , length: 20                    , notnull: false                                                       }        
    tooth:                             { type: string   , length: 50                    , notnull: false                                                       }
    diagnosis:                         { type: string   , length: 5000                  , notnull: false                                                       }
    treatment:                         { type: string   , length: 5000                  , notnull: false                                                       }
    active:                            { type: string   , length: 1  , fixed: true      , notnull: true , default: 1                                           }
  indexes:
    i_active:                          { fields: [ active ]                                                                                                    }
  relations:
    Patient:                           { class: Patient , local  : patient_id   , foreign: id       , type: one , alias:  Patient   , onDelete: CASCADE, onUpdate: CASCADE }
  options:
    symfony:                           { filter: false, form: true }
    boolean_columns:                   [ active ]
    